#!/bin/bash

if [ $# -lt 1 ]
then
cat <<EOF >&1
usage: $0 <commit-msg> [ignore-pattern]
EOF
exit 1
fi

for d in $(git status -s | cut -d' ' -f 3 | sed '/*$2*/d' | rev | cut -d '/' -f 2- | rev)                    
do          
git add $d
git commit -m "$1 in $(echo $d | rev | cut -d '/' -f 1 | rev)"
done
